redis:
  addr: "localhost:6389"

grpc:
  server:
    port: 8014
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"

kafka:
  addrs:
    - "localhost:9094"

elasticsearch:
  urls: "https://localhost:9200"
  sniff: false


opentelemetry:
  serviceName: "demo"
  serviceVersion: "v0.0.1"

logger:
  filename: "d:\\appcache\\elasticsearch\\logs\\search  .log"
  maxsize: 50
  maxBackups: 3
  maxAge: 7

zipkin:
  collectorURL: "http://localhost:9411/api/v2/spans"

prometheus:
  listenPort: ":8081"

remoteProvider:
  provider: "etcd3"
  endpoint: "http://127.0.0.1:12379"
  path: "/reward"
